### ISSUE TITLE
Migration from Snowpack to Vite?

### ISSUE THREAD

**Issue by seirl** [kevinclement/SimpleArmory#358]
@kevinclement when I run `npm run dev` I get:

```
SvelteKit now uses https://vitejs.dev. Please remove snowpack.config.js and put Vite config in svelte.config.cjs: https://kit.svelte.dev/docs#configuration-vite
config.kit.adapter should be an object with an "adapt" method, rather than the name of an adapter. See https://kit.svelte.dev/docs#adapters
Error: config.kit.adapter should be an object with an "adapt" method, rather than the name of an adapter. See https://kit.svelte.dev/docs#adapters
    at Object.validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:188:13)
    at validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:518:28)
    at validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:516:19)
    at validate_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:587:20)
    at load_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:558:20)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async get_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:616:10)
    at async file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:679:18
```

Any idea how we can migrate this?

**Comment by seirl** [comment]
@kevinclement reping, the error changed now:

```
svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module. See https://kit.svelte.dev/docs#configuration for an example
config.kit.adapter should be an object with an "adapt" method, rather than the name of an adapter. See https://kit.svelte.dev/docs#adapters
Error: config.kit.adapter should be an object with an "adapt" method, rather than the name of an adapter. See https://kit.svelte.dev/docs#adapters
    at Object.validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:332:13)
    at validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:583:28)
    at validate (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:581:19)
    at validate_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:670:20)
    at load_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:647:20)
    at async get_config (file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:790:10)
    at async file:///home/antoine/contrib/SimpleArmory/node_modules/@sveltejs/kit/dist/cli.js:875:18
```
